export const BANK_LOGIN_REQUEST = "BANK_LOGIN_REQUEST";
export const BANK_LOGIN_SUCCESS = "BANK_LOGIN_SUCCESS";
export const BANK_LOGIN_FAIL = "BANK_LOGIN_FAIL";

export const BANK_REGISTER_USER_REQUEST = "BANK_REGISTER_USER_REQUEST";
export const BANK_REGISTER_USER_SUCCESS = "BANK_REGISTER_USER_SUCCESS";
export const BANK_REGISTER_USER_FAIL = "BANK_REGISTER_USER_FAIL";

export const BANK_LOAD_USER_REQUEST = "BANK_LOAD_USER_REQUEST";
export const BANK_LOAD_USER_SUCCESS = "BANK_LOAD_USER_SUCCESS";
export const BANK_LOAD_USER_FAIL = "BANK_LOAD_USER_FAIL";

export const BANK_LOGOUT_SUCCESS = "BANK_LOGOUT_SUCCESS";
export const BANK_LOGOUT_FAIL = "BANK_LOGOUT_FAIL";



;

// export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
// export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
// export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const BANK_USER_DETAILS_REQUEST = "BANK_USER_DETAILS_REQUEST";
export const BANK_USER_DETAILS_SUCCESS = "BANK_USER_DETAILS_SUCCESS";
export const BANK_USER_DETAILS_FAIL = "BANK_USER_DETAILS_FAIL";



// export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
// export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
// export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
// export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
